/**
 * helperData.ts — country reference table used by the contagion helper.
 * Source: mledoze/countries (public domain). One row per ISO-3 territory:
 *   iso3, common name, French name, [lat,lng] centroid, land-border ISO-3
 *   list, region, landlocked flag, area (km², rough size/weight proxy).
 * Auto-generated — do not hand-edit; regenerate from the source instead.
 */
export interface Country {
  iso3: string;
  name: string;
  nameFr: string;
  lat: number;
  lng: number;
  borders: string[];
  region: string;
  landlocked: boolean;
  area: number;
}

export const COUNTRIES: Country[] = [
  { iso3: "ABW", name: "Aruba", nameFr: "Aruba", lat: 12.5, lng: -69.97, borders: [], region: "Americas", landlocked: false, area: 180 },
  { iso3: "AFG", name: "Afghanistan", nameFr: "Afghanistan", lat: 33, lng: 65, borders: ["IRN","PAK","TKM","UZB","TJK","CHN"], region: "Asia", landlocked: true, area: 652230 },
  { iso3: "AGO", name: "Angola", nameFr: "Angola", lat: -12.5, lng: 18.5, borders: ["COG","COD","ZMB","NAM"], region: "Africa", landlocked: false, area: 1246700 },
  { iso3: "AIA", name: "Anguilla", nameFr: "Anguilla", lat: 18.25, lng: -63.17, borders: [], region: "Americas", landlocked: false, area: 91 },
  { iso3: "ALA", name: "Åland Islands", nameFr: "Ahvenanmaa", lat: 60.12, lng: 19.9, borders: [], region: "Europe", landlocked: false, area: 1580 },
  { iso3: "ALB", name: "Albania", nameFr: "Albanie", lat: 41, lng: 20, borders: ["MNE","GRC","MKD","UNK"], region: "Europe", landlocked: false, area: 28748 },
  { iso3: "AND", name: "Andorra", nameFr: "Andorre", lat: 42.5, lng: 1.5, borders: ["FRA","ESP"], region: "Europe", landlocked: true, area: 468 },
  { iso3: "ARE", name: "United Arab Emirates", nameFr: "Émirats arabes unis", lat: 24, lng: 54, borders: ["OMN","SAU"], region: "Asia", landlocked: false, area: 83600 },
  { iso3: "ARG", name: "Argentina", nameFr: "Argentine", lat: -34, lng: -64, borders: ["BOL","BRA","CHL","PRY","URY"], region: "Americas", landlocked: false, area: 2780400 },
  { iso3: "ARM", name: "Armenia", nameFr: "Arménie", lat: 40, lng: 45, borders: ["AZE","GEO","IRN","TUR"], region: "Asia", landlocked: true, area: 29743 },
  { iso3: "ASM", name: "American Samoa", nameFr: "Samoa américaines", lat: -14.33, lng: -170, borders: [], region: "Oceania", landlocked: false, area: 199 },
  { iso3: "ATA", name: "Antarctica", nameFr: "Antarctique", lat: -90, lng: 0, borders: [], region: "Antarctic", landlocked: false, area: 14000000 },
  { iso3: "ATF", name: "French Southern and Antarctic Lands", nameFr: "Terres australes et antarctiques françaises", lat: -49.25, lng: 69.17, borders: [], region: "Antarctic", landlocked: false, area: 7747 },
  { iso3: "ATG", name: "Antigua and Barbuda", nameFr: "Antigua-et-Barbuda", lat: 17.05, lng: -61.8, borders: [], region: "Americas", landlocked: false, area: 442 },
  { iso3: "AUS", name: "Australia", nameFr: "Australie", lat: -27, lng: 133, borders: [], region: "Oceania", landlocked: false, area: 7692024 },
  { iso3: "AUT", name: "Austria", nameFr: "Autriche", lat: 47.33, lng: 13.33, borders: ["CZE","DEU","HUN","ITA","LIE","SVK","SVN","CHE"], region: "Europe", landlocked: true, area: 83871 },
  { iso3: "AZE", name: "Azerbaijan", nameFr: "Azerbaïdjan", lat: 40.5, lng: 47.5, borders: ["ARM","GEO","IRN","RUS","TUR"], region: "Asia", landlocked: true, area: 86600 },
  { iso3: "BDI", name: "Burundi", nameFr: "Burundi", lat: -3.5, lng: 30, borders: ["COD","RWA","TZA"], region: "Africa", landlocked: true, area: 27834 },
  { iso3: "BEL", name: "Belgium", nameFr: "Belgique", lat: 50.83, lng: 4, borders: ["FRA","DEU","LUX","NLD"], region: "Europe", landlocked: false, area: 30528 },
  { iso3: "BEN", name: "Benin", nameFr: "Bénin", lat: 9.5, lng: 2.25, borders: ["BFA","NER","NGA","TGO"], region: "Africa", landlocked: false, area: 112622 },
  { iso3: "BES", name: "Caribbean Netherlands", nameFr: "Pays-Bas caribéens", lat: 12.18, lng: -68.25, borders: [], region: "Americas", landlocked: false, area: 328 },
  { iso3: "BFA", name: "Burkina Faso", nameFr: "Burkina Faso", lat: 13, lng: -2, borders: ["BEN","CIV","GHA","MLI","NER","TGO"], region: "Africa", landlocked: true, area: 272967 },
  { iso3: "BGD", name: "Bangladesh", nameFr: "Bangladesh", lat: 24, lng: 90, borders: ["MMR","IND"], region: "Asia", landlocked: false, area: 147570 },
  { iso3: "BGR", name: "Bulgaria", nameFr: "Bulgarie", lat: 43, lng: 25, borders: ["GRC","MKD","ROU","SRB","TUR"], region: "Europe", landlocked: false, area: 110879 },
  { iso3: "BHR", name: "Bahrain", nameFr: "Bahreïn", lat: 26, lng: 50.55, borders: [], region: "Asia", landlocked: false, area: 765 },
  { iso3: "BHS", name: "Bahamas", nameFr: "Bahamas", lat: 24.25, lng: -76, borders: [], region: "Americas", landlocked: false, area: 13943 },
  { iso3: "BIH", name: "Bosnia and Herzegovina", nameFr: "Bosnie-Herzégovine", lat: 44, lng: 18, borders: ["HRV","MNE","SRB"], region: "Europe", landlocked: false, area: 51209 },
  { iso3: "BLM", name: "Saint Barthélemy", nameFr: "Saint-Barthélemy", lat: 18.5, lng: -63.42, borders: [], region: "Americas", landlocked: false, area: 21 },
  { iso3: "BLR", name: "Belarus", nameFr: "Biélorussie", lat: 53, lng: 28, borders: ["LVA","LTU","POL","RUS","UKR"], region: "Europe", landlocked: true, area: 207600 },
  { iso3: "BLZ", name: "Belize", nameFr: "Belize", lat: 17.25, lng: -88.75, borders: ["GTM","MEX"], region: "Americas", landlocked: false, area: 22966 },
  { iso3: "BMU", name: "Bermuda", nameFr: "Bermudes", lat: 32.33, lng: -64.75, borders: [], region: "Americas", landlocked: false, area: 54 },
  { iso3: "BOL", name: "Bolivia", nameFr: "Bolivie", lat: -17, lng: -65, borders: ["ARG","BRA","CHL","PRY","PER"], region: "Americas", landlocked: true, area: 1098581 },
  { iso3: "BRA", name: "Brazil", nameFr: "Brésil", lat: -10, lng: -55, borders: ["ARG","BOL","COL","GUF","GUY","PRY","PER","SUR","URY","VEN"], region: "Americas", landlocked: false, area: 8515767 },
  { iso3: "BRB", name: "Barbados", nameFr: "Barbade", lat: 13.17, lng: -59.53, borders: [], region: "Americas", landlocked: false, area: 430 },
  { iso3: "BRN", name: "Brunei", nameFr: "Brunei", lat: 4.5, lng: 114.67, borders: ["MYS"], region: "Asia", landlocked: false, area: 5765 },
  { iso3: "BTN", name: "Bhutan", nameFr: "Bhoutan", lat: 27.5, lng: 90.5, borders: ["CHN","IND"], region: "Asia", landlocked: true, area: 38394 },
  { iso3: "BVT", name: "Bouvet Island", nameFr: "Île Bouvet", lat: -54.43, lng: 3.4, borders: [], region: "Antarctic", landlocked: false, area: 49 },
  { iso3: "BWA", name: "Botswana", nameFr: "Botswana", lat: -22, lng: 24, borders: ["NAM","ZAF","ZMB","ZWE"], region: "Africa", landlocked: true, area: 582000 },
  { iso3: "CAF", name: "Central African Republic", nameFr: "République centrafricaine", lat: 7, lng: 21, borders: ["CMR","TCD","COD","COG","SSD","SDN"], region: "Africa", landlocked: true, area: 622984 },
  { iso3: "CAN", name: "Canada", nameFr: "Canada", lat: 60, lng: -95, borders: ["USA"], region: "Americas", landlocked: false, area: 9984670 },
  { iso3: "CCK", name: "Cocos (Keeling) Islands", nameFr: "Îles Cocos", lat: -12.5, lng: 96.83, borders: [], region: "Oceania", landlocked: false, area: 14 },
  { iso3: "CHE", name: "Switzerland", nameFr: "Suisse", lat: 47, lng: 8, borders: ["AUT","FRA","ITA","LIE","DEU"], region: "Europe", landlocked: true, area: 41284 },
  { iso3: "CHL", name: "Chile", nameFr: "Chili", lat: -30, lng: -71, borders: ["ARG","BOL","PER"], region: "Americas", landlocked: false, area: 756102 },
  { iso3: "CHN", name: "China", nameFr: "Chine", lat: 35, lng: 105, borders: ["AFG","BTN","MMR","HKG","IND","KAZ","NPL","PRK","KGZ","LAO","MAC","MNG","PAK","RUS","TJK","VNM"], region: "Asia", landlocked: false, area: 9706961 },
  { iso3: "CIV", name: "Ivory Coast", nameFr: "Côte d'Ivoire", lat: 8, lng: -5, borders: ["BFA","GHA","GIN","LBR","MLI"], region: "Africa", landlocked: false, area: 322463 },
  { iso3: "CMR", name: "Cameroon", nameFr: "Cameroun", lat: 6, lng: 12, borders: ["CAF","TCD","COG","GNQ","GAB","NGA"], region: "Africa", landlocked: false, area: 475442 },
  { iso3: "COD", name: "DR Congo", nameFr: "Congo (Rép. dém.)", lat: 0, lng: 25, borders: ["AGO","BDI","CAF","COG","RWA","SSD","TZA","UGA","ZMB"], region: "Africa", landlocked: false, area: 2344858 },
  { iso3: "COG", name: "Congo", nameFr: "Congo", lat: -1, lng: 15, borders: ["AGO","CMR","CAF","COD","GAB"], region: "Africa", landlocked: false, area: 342000 },
  { iso3: "COK", name: "Cook Islands", nameFr: "Îles Cook", lat: -21.23, lng: -159.77, borders: [], region: "Oceania", landlocked: false, area: 236 },
  { iso3: "COL", name: "Colombia", nameFr: "Colombie", lat: 4, lng: -72, borders: ["BRA","ECU","PAN","PER","VEN"], region: "Americas", landlocked: false, area: 1141748 },
  { iso3: "COM", name: "Comoros", nameFr: "Comores", lat: -12.17, lng: 44.25, borders: [], region: "Africa", landlocked: false, area: 1862 },
  { iso3: "CPV", name: "Cape Verde", nameFr: "Îles du Cap-Vert", lat: 16, lng: -24, borders: [], region: "Africa", landlocked: false, area: 4033 },
  { iso3: "CRI", name: "Costa Rica", nameFr: "Costa Rica", lat: 10, lng: -84, borders: ["NIC","PAN"], region: "Americas", landlocked: false, area: 51100 },
  { iso3: "CUB", name: "Cuba", nameFr: "Cuba", lat: 21.5, lng: -80, borders: [], region: "Americas", landlocked: false, area: 109884 },
  { iso3: "CUW", name: "Curaçao", nameFr: "Curaçao", lat: 12.12, lng: -68.93, borders: [], region: "Americas", landlocked: false, area: 444 },
  { iso3: "CXR", name: "Christmas Island", nameFr: "Île Christmas", lat: -10.5, lng: 105.67, borders: [], region: "Oceania", landlocked: false, area: 135 },
  { iso3: "CYM", name: "Cayman Islands", nameFr: "Îles Caïmans", lat: 19.5, lng: -80.5, borders: [], region: "Americas", landlocked: false, area: 264 },
  { iso3: "CYP", name: "Cyprus", nameFr: "Chypre", lat: 35, lng: 33, borders: [], region: "Europe", landlocked: false, area: 9251 },
  { iso3: "CZE", name: "Czechia", nameFr: "Tchéquie", lat: 49.75, lng: 15.5, borders: ["AUT","DEU","POL","SVK"], region: "Europe", landlocked: true, area: 78865 },
  { iso3: "DEU", name: "Germany", nameFr: "Allemagne", lat: 51, lng: 9, borders: ["AUT","BEL","CZE","DNK","FRA","LUX","NLD","POL","CHE"], region: "Europe", landlocked: false, area: 357114 },
  { iso3: "DJI", name: "Djibouti", nameFr: "Djibouti", lat: 11.5, lng: 43, borders: ["ERI","ETH","SOM"], region: "Africa", landlocked: false, area: 23200 },
  { iso3: "DMA", name: "Dominica", nameFr: "Dominique", lat: 15.42, lng: -61.33, borders: [], region: "Americas", landlocked: false, area: 751 },
  { iso3: "DNK", name: "Denmark", nameFr: "Danemark", lat: 56, lng: 10, borders: ["DEU"], region: "Europe", landlocked: false, area: 43094 },
  { iso3: "DOM", name: "Dominican Republic", nameFr: "République dominicaine", lat: 19, lng: -70.67, borders: ["HTI"], region: "Americas", landlocked: false, area: 48671 },
  { iso3: "DZA", name: "Algeria", nameFr: "Algérie", lat: 28, lng: 3, borders: ["TUN","LBY","NER","ESH","MRT","MLI","MAR"], region: "Africa", landlocked: false, area: 2381741 },
  { iso3: "ECU", name: "Ecuador", nameFr: "Équateur", lat: -2, lng: -77.5, borders: ["COL","PER"], region: "Americas", landlocked: false, area: 276841 },
  { iso3: "EGY", name: "Egypt", nameFr: "Égypte", lat: 27, lng: 30, borders: ["ISR","LBY","PSE","SDN"], region: "Africa", landlocked: false, area: 1002450 },
  { iso3: "ERI", name: "Eritrea", nameFr: "Érythrée", lat: 15, lng: 39, borders: ["DJI","ETH","SDN"], region: "Africa", landlocked: false, area: 117600 },
  { iso3: "ESH", name: "Western Sahara", nameFr: "Sahara Occidental", lat: 24.5, lng: -13, borders: ["DZA","MRT","MAR"], region: "Africa", landlocked: false, area: 266000 },
  { iso3: "ESP", name: "Spain", nameFr: "Espagne", lat: 40, lng: -4, borders: ["AND","FRA","GIB","PRT","MAR"], region: "Europe", landlocked: false, area: 505992 },
  { iso3: "EST", name: "Estonia", nameFr: "Estonie", lat: 59, lng: 26, borders: ["LVA","RUS"], region: "Europe", landlocked: false, area: 45227 },
  { iso3: "ETH", name: "Ethiopia", nameFr: "Éthiopie", lat: 8, lng: 38, borders: ["DJI","ERI","KEN","SOM","SSD","SDN"], region: "Africa", landlocked: true, area: 1104300 },
  { iso3: "FIN", name: "Finland", nameFr: "Finlande", lat: 64, lng: 26, borders: ["NOR","SWE","RUS"], region: "Europe", landlocked: false, area: 338424 },
  { iso3: "FJI", name: "Fiji", nameFr: "Fidji", lat: -18, lng: 175, borders: [], region: "Oceania", landlocked: false, area: 18272 },
  { iso3: "FLK", name: "Falkland Islands", nameFr: "Îles Malouines", lat: -51.75, lng: -59, borders: [], region: "Americas", landlocked: false, area: 12173 },
  { iso3: "FRA", name: "France", nameFr: "France", lat: 46, lng: 2, borders: ["AND","BEL","DEU","ITA","LUX","MCO","ESP","CHE"], region: "Europe", landlocked: false, area: 551695 },
  { iso3: "FRO", name: "Faroe Islands", nameFr: "Îles Féroé", lat: 62, lng: -7, borders: [], region: "Europe", landlocked: false, area: 1393 },
  { iso3: "FSM", name: "Micronesia", nameFr: "Micronésie", lat: 6.92, lng: 158.25, borders: [], region: "Oceania", landlocked: false, area: 702 },
  { iso3: "GAB", name: "Gabon", nameFr: "Gabon", lat: -1, lng: 11.75, borders: ["CMR","COG","GNQ"], region: "Africa", landlocked: false, area: 267668 },
  { iso3: "GBR", name: "United Kingdom", nameFr: "Royaume-Uni", lat: 54, lng: -2, borders: ["IRL"], region: "Europe", landlocked: false, area: 242900 },
  { iso3: "GEO", name: "Georgia", nameFr: "Géorgie", lat: 42, lng: 43.5, borders: ["ARM","AZE","RUS","TUR"], region: "Asia", landlocked: false, area: 69700 },
  { iso3: "GGY", name: "Guernsey", nameFr: "Guernesey", lat: 49.47, lng: -2.58, borders: [], region: "Europe", landlocked: false, area: 78 },
  { iso3: "GHA", name: "Ghana", nameFr: "Ghana", lat: 8, lng: -2, borders: ["BFA","CIV","TGO"], region: "Africa", landlocked: false, area: 238533 },
  { iso3: "GIB", name: "Gibraltar", nameFr: "Gibraltar", lat: 36.13, lng: -5.35, borders: ["ESP"], region: "Europe", landlocked: false, area: 6 },
  { iso3: "GIN", name: "Guinea", nameFr: "Guinée", lat: 11, lng: -10, borders: ["CIV","GNB","LBR","MLI","SEN","SLE"], region: "Africa", landlocked: false, area: 245857 },
  { iso3: "GLP", name: "Guadeloupe", nameFr: "Guadeloupe", lat: 16.25, lng: -61.58, borders: [], region: "Americas", landlocked: false, area: 1628 },
  { iso3: "GMB", name: "Gambia", nameFr: "Gambie", lat: 13.47, lng: -16.57, borders: ["SEN"], region: "Africa", landlocked: false, area: 10689 },
  { iso3: "GNB", name: "Guinea-Bissau", nameFr: "Guinée-Bissau", lat: 12, lng: -15, borders: ["GIN","SEN"], region: "Africa", landlocked: false, area: 36125 },
  { iso3: "GNQ", name: "Equatorial Guinea", nameFr: "Guinée équatoriale", lat: 2, lng: 10, borders: ["CMR","GAB"], region: "Africa", landlocked: false, area: 28051 },
  { iso3: "GRC", name: "Greece", nameFr: "Grèce", lat: 39, lng: 22, borders: ["ALB","BGR","TUR","MKD"], region: "Europe", landlocked: false, area: 131990 },
  { iso3: "GRD", name: "Grenada", nameFr: "Grenade", lat: 12.12, lng: -61.67, borders: [], region: "Americas", landlocked: false, area: 344 },
  { iso3: "GRL", name: "Greenland", nameFr: "Groenland", lat: 72, lng: -40, borders: [], region: "Americas", landlocked: false, area: 2166086 },
  { iso3: "GTM", name: "Guatemala", nameFr: "Guatemala", lat: 15.5, lng: -90.25, borders: ["BLZ","SLV","HND","MEX"], region: "Americas", landlocked: false, area: 108889 },
  { iso3: "GUF", name: "French Guiana", nameFr: "Guyane", lat: 4, lng: -53, borders: ["BRA","SUR"], region: "Americas", landlocked: false, area: 83534 },
  { iso3: "GUM", name: "Guam", nameFr: "Guam", lat: 13.47, lng: 144.78, borders: [], region: "Oceania", landlocked: false, area: 549 },
  { iso3: "GUY", name: "Guyana", nameFr: "Guyana", lat: 5, lng: -59, borders: ["BRA","SUR","VEN"], region: "Americas", landlocked: false, area: 214969 },
  { iso3: "HKG", name: "Hong Kong", nameFr: "Hong Kong", lat: 22.27, lng: 114.19, borders: ["CHN"], region: "Asia", landlocked: false, area: 1104 },
  { iso3: "HMD", name: "Heard Island and McDonald Islands", nameFr: "Îles Heard-et-MacDonald", lat: -53.1, lng: 72.52, borders: [], region: "Antarctic", landlocked: false, area: 412 },
  { iso3: "HND", name: "Honduras", nameFr: "Honduras", lat: 15, lng: -86.5, borders: ["GTM","SLV","NIC"], region: "Americas", landlocked: false, area: 112492 },
  { iso3: "HRV", name: "Croatia", nameFr: "Croatie", lat: 45.17, lng: 15.5, borders: ["BIH","HUN","MNE","SRB","SVN"], region: "Europe", landlocked: false, area: 56594 },
  { iso3: "HTI", name: "Haiti", nameFr: "Haïti", lat: 19, lng: -72.42, borders: ["DOM"], region: "Americas", landlocked: false, area: 27750 },
  { iso3: "HUN", name: "Hungary", nameFr: "Hongrie", lat: 47, lng: 20, borders: ["AUT","HRV","ROU","SRB","SVK","SVN","UKR"], region: "Europe", landlocked: true, area: 93028 },
  { iso3: "IDN", name: "Indonesia", nameFr: "Indonésie", lat: -5, lng: 120, borders: ["TLS","MYS","PNG"], region: "Asia", landlocked: false, area: 1904569 },
  { iso3: "IMN", name: "Isle of Man", nameFr: "Île de Man", lat: 54.25, lng: -4.5, borders: [], region: "Europe", landlocked: false, area: 572 },
  { iso3: "IND", name: "India", nameFr: "Inde", lat: 20, lng: 77, borders: ["BGD","BTN","MMR","CHN","NPL","PAK"], region: "Asia", landlocked: false, area: 3287590 },
  { iso3: "IOT", name: "British Indian Ocean Territory", nameFr: "Territoire britannique de l'océan Indien", lat: -6, lng: 71.5, borders: [], region: "Africa", landlocked: false, area: 60 },
  { iso3: "IRL", name: "Ireland", nameFr: "Irlande", lat: 53, lng: -8, borders: ["GBR"], region: "Europe", landlocked: false, area: 70273 },
  { iso3: "IRN", name: "Iran", nameFr: "Iran", lat: 32, lng: 53, borders: ["AFG","ARM","AZE","IRQ","PAK","TUR","TKM"], region: "Asia", landlocked: false, area: 1648195 },
  { iso3: "IRQ", name: "Iraq", nameFr: "Irak", lat: 33, lng: 44, borders: ["IRN","JOR","KWT","SAU","SYR","TUR"], region: "Asia", landlocked: false, area: 438317 },
  { iso3: "ISL", name: "Iceland", nameFr: "Islande", lat: 65, lng: -18, borders: [], region: "Europe", landlocked: false, area: 103000 },
  { iso3: "ISR", name: "Israel", nameFr: "Israël", lat: 31.47, lng: 35.13, borders: ["EGY","JOR","LBN","PSE","SYR"], region: "Asia", landlocked: false, area: 20770 },
  { iso3: "ITA", name: "Italy", nameFr: "Italie", lat: 42.83, lng: 12.83, borders: ["AUT","FRA","SMR","SVN","CHE","VAT"], region: "Europe", landlocked: false, area: 301336 },
  { iso3: "JAM", name: "Jamaica", nameFr: "Jamaïque", lat: 18.25, lng: -77.5, borders: [], region: "Americas", landlocked: false, area: 10991 },
  { iso3: "JEY", name: "Jersey", nameFr: "Jersey", lat: 49.25, lng: -2.17, borders: [], region: "Europe", landlocked: false, area: 116 },
  { iso3: "JOR", name: "Jordan", nameFr: "Jordanie", lat: 31, lng: 36, borders: ["IRQ","ISR","PSE","SAU","SYR"], region: "Asia", landlocked: false, area: 89342 },
  { iso3: "JPN", name: "Japan", nameFr: "Japon", lat: 36, lng: 138, borders: [], region: "Asia", landlocked: false, area: 377930 },
  { iso3: "KAZ", name: "Kazakhstan", nameFr: "Kazakhstan", lat: 48, lng: 68, borders: ["CHN","KGZ","RUS","TKM","UZB"], region: "Asia", landlocked: true, area: 2724900 },
  { iso3: "KEN", name: "Kenya", nameFr: "Kenya", lat: 1, lng: 38, borders: ["ETH","SOM","SSD","TZA","UGA"], region: "Africa", landlocked: false, area: 580367 },
  { iso3: "KGZ", name: "Kyrgyzstan", nameFr: "Kirghizistan", lat: 41, lng: 75, borders: ["CHN","KAZ","TJK","UZB"], region: "Asia", landlocked: true, area: 199951 },
  { iso3: "KHM", name: "Cambodia", nameFr: "Cambodge", lat: 13, lng: 105, borders: ["LAO","THA","VNM"], region: "Asia", landlocked: false, area: 181035 },
  { iso3: "KIR", name: "Kiribati", nameFr: "Kiribati", lat: 1.42, lng: 173, borders: [], region: "Oceania", landlocked: false, area: 811 },
  { iso3: "KNA", name: "Saint Kitts and Nevis", nameFr: "Saint-Christophe-et-Niévès", lat: 17.33, lng: -62.75, borders: [], region: "Americas", landlocked: false, area: 261 },
  { iso3: "KOR", name: "South Korea", nameFr: "Corée du Sud", lat: 37, lng: 127.5, borders: ["PRK"], region: "Asia", landlocked: false, area: 100210 },
  { iso3: "KWT", name: "Kuwait", nameFr: "Koweït", lat: 29.5, lng: 45.75, borders: ["IRQ","SAU"], region: "Asia", landlocked: false, area: 17818 },
  { iso3: "LAO", name: "Laos", nameFr: "Laos", lat: 18, lng: 105, borders: ["MMR","KHM","CHN","THA","VNM"], region: "Asia", landlocked: true, area: 236800 },
  { iso3: "LBN", name: "Lebanon", nameFr: "Liban", lat: 33.83, lng: 35.83, borders: ["ISR","SYR"], region: "Asia", landlocked: false, area: 10452 },
  { iso3: "LBR", name: "Liberia", nameFr: "Liberia", lat: 6.5, lng: -9.5, borders: ["GIN","CIV","SLE"], region: "Africa", landlocked: false, area: 111369 },
  { iso3: "LBY", name: "Libya", nameFr: "Libye", lat: 25, lng: 17, borders: ["DZA","TCD","EGY","NER","SDN","TUN"], region: "Africa", landlocked: false, area: 1759540 },
  { iso3: "LCA", name: "Saint Lucia", nameFr: "Sainte-Lucie", lat: 13.88, lng: -60.97, borders: [], region: "Americas", landlocked: false, area: 616 },
  { iso3: "LIE", name: "Liechtenstein", nameFr: "Liechtenstein", lat: 47.27, lng: 9.53, borders: ["AUT","CHE"], region: "Europe", landlocked: true, area: 160 },
  { iso3: "LKA", name: "Sri Lanka", nameFr: "Sri Lanka", lat: 7, lng: 81, borders: ["IND"], region: "Asia", landlocked: false, area: 65610 },
  { iso3: "LSO", name: "Lesotho", nameFr: "Lesotho", lat: -29.5, lng: 28.5, borders: ["ZAF"], region: "Africa", landlocked: true, area: 30355 },
  { iso3: "LTU", name: "Lithuania", nameFr: "Lituanie", lat: 56, lng: 24, borders: ["BLR","LVA","POL","RUS"], region: "Europe", landlocked: false, area: 65300 },
  { iso3: "LUX", name: "Luxembourg", nameFr: "Luxembourg", lat: 49.75, lng: 6.17, borders: ["BEL","FRA","DEU"], region: "Europe", landlocked: true, area: 2586 },
  { iso3: "LVA", name: "Latvia", nameFr: "Lettonie", lat: 57, lng: 25, borders: ["BLR","EST","LTU","RUS"], region: "Europe", landlocked: false, area: 64559 },
  { iso3: "MAC", name: "Macau", nameFr: "Macao", lat: 22.17, lng: 113.55, borders: ["CHN"], region: "Asia", landlocked: false, area: 30 },
  { iso3: "MAF", name: "Saint Martin", nameFr: "Saint-Martin", lat: 18.08, lng: -63.95, borders: ["SXM"], region: "Americas", landlocked: false, area: 53 },
  { iso3: "MAR", name: "Morocco", nameFr: "Maroc", lat: 32, lng: -5, borders: ["DZA","ESH","ESP"], region: "Africa", landlocked: false, area: 446550 },
  { iso3: "MCO", name: "Monaco", nameFr: "Monaco", lat: 43.73, lng: 7.4, borders: ["FRA"], region: "Europe", landlocked: false, area: 2 },
  { iso3: "MDA", name: "Moldova", nameFr: "Moldavie", lat: 47, lng: 29, borders: ["ROU","UKR"], region: "Europe", landlocked: true, area: 33846 },
  { iso3: "MDG", name: "Madagascar", nameFr: "Madagascar", lat: -20, lng: 47, borders: [], region: "Africa", landlocked: false, area: 587041 },
  { iso3: "MDV", name: "Maldives", nameFr: "Maldives", lat: 3.25, lng: 73, borders: [], region: "Asia", landlocked: false, area: 300 },
  { iso3: "MEX", name: "Mexico", nameFr: "Mexique", lat: 23, lng: -102, borders: ["BLZ","GTM","USA"], region: "Americas", landlocked: false, area: 1964375 },
  { iso3: "MHL", name: "Marshall Islands", nameFr: "Îles Marshall", lat: 9, lng: 168, borders: [], region: "Oceania", landlocked: false, area: 181 },
  { iso3: "MKD", name: "North Macedonia", nameFr: "Macédoine du Nord", lat: 41.83, lng: 22, borders: ["ALB","BGR","GRC","UNK","SRB"], region: "Europe", landlocked: true, area: 25713 },
  { iso3: "MLI", name: "Mali", nameFr: "Mali", lat: 17, lng: -4, borders: ["DZA","BFA","GIN","CIV","MRT","NER","SEN"], region: "Africa", landlocked: true, area: 1240192 },
  { iso3: "MLT", name: "Malta", nameFr: "Malte", lat: 35.83, lng: 14.58, borders: [], region: "Europe", landlocked: false, area: 316 },
  { iso3: "MMR", name: "Myanmar", nameFr: "Birmanie", lat: 22, lng: 98, borders: ["BGD","CHN","IND","LAO","THA"], region: "Asia", landlocked: false, area: 676578 },
  { iso3: "MNE", name: "Montenegro", nameFr: "Monténégro", lat: 42.5, lng: 19.3, borders: ["ALB","BIH","HRV","UNK","SRB"], region: "Europe", landlocked: false, area: 13812 },
  { iso3: "MNG", name: "Mongolia", nameFr: "Mongolie", lat: 46, lng: 105, borders: ["CHN","RUS"], region: "Asia", landlocked: true, area: 1564110 },
  { iso3: "MNP", name: "Northern Mariana Islands", nameFr: "Îles Mariannes du Nord", lat: 15.2, lng: 145.75, borders: [], region: "Oceania", landlocked: false, area: 464 },
  { iso3: "MOZ", name: "Mozambique", nameFr: "Mozambique", lat: -18.25, lng: 35, borders: ["MWI","ZAF","SWZ","TZA","ZMB","ZWE"], region: "Africa", landlocked: false, area: 801590 },
  { iso3: "MRT", name: "Mauritania", nameFr: "Mauritanie", lat: 20, lng: -12, borders: ["DZA","MLI","SEN","ESH"], region: "Africa", landlocked: false, area: 1030700 },
  { iso3: "MSR", name: "Montserrat", nameFr: "Montserrat", lat: 16.75, lng: -62.2, borders: [], region: "Americas", landlocked: false, area: 102 },
  { iso3: "MTQ", name: "Martinique", nameFr: "Martinique", lat: 14.67, lng: -61, borders: [], region: "Americas", landlocked: false, area: 1128 },
  { iso3: "MUS", name: "Mauritius", nameFr: "Île Maurice", lat: -20.28, lng: 57.55, borders: [], region: "Africa", landlocked: false, area: 2040 },
  { iso3: "MWI", name: "Malawi", nameFr: "Malawi", lat: -13.5, lng: 34, borders: ["MOZ","TZA","ZMB"], region: "Africa", landlocked: true, area: 118484 },
  { iso3: "MYS", name: "Malaysia", nameFr: "Malaisie", lat: 2.5, lng: 112.5, borders: ["BRN","IDN","THA"], region: "Asia", landlocked: false, area: 330803 },
  { iso3: "MYT", name: "Mayotte", nameFr: "Mayotte", lat: -12.83, lng: 45.17, borders: [], region: "Africa", landlocked: false, area: 374 },
  { iso3: "NAM", name: "Namibia", nameFr: "Namibie", lat: -22, lng: 17, borders: ["AGO","BWA","ZAF","ZMB"], region: "Africa", landlocked: false, area: 825615 },
  { iso3: "NCL", name: "New Caledonia", nameFr: "Nouvelle-Calédonie", lat: -21.5, lng: 165.5, borders: [], region: "Oceania", landlocked: false, area: 18575 },
  { iso3: "NER", name: "Niger", nameFr: "Niger", lat: 16, lng: 8, borders: ["DZA","BEN","BFA","TCD","LBY","MLI","NGA"], region: "Africa", landlocked: true, area: 1267000 },
  { iso3: "NFK", name: "Norfolk Island", nameFr: "Île Norfolk", lat: -29.03, lng: 167.95, borders: [], region: "Oceania", landlocked: false, area: 36 },
  { iso3: "NGA", name: "Nigeria", nameFr: "Nigéria", lat: 10, lng: 8, borders: ["BEN","CMR","TCD","NER"], region: "Africa", landlocked: false, area: 923768 },
  { iso3: "NIC", name: "Nicaragua", nameFr: "Nicaragua", lat: 13, lng: -85, borders: ["CRI","HND"], region: "Americas", landlocked: false, area: 130373 },
  { iso3: "NIU", name: "Niue", nameFr: "Niue", lat: -19.03, lng: -169.87, borders: [], region: "Oceania", landlocked: false, area: 260 },
  { iso3: "NLD", name: "Netherlands", nameFr: "Pays-Bas", lat: 52.5, lng: 5.75, borders: ["BEL","DEU"], region: "Europe", landlocked: false, area: 41850 },
  { iso3: "NOR", name: "Norway", nameFr: "Norvège", lat: 62, lng: 10, borders: ["FIN","SWE","RUS"], region: "Europe", landlocked: false, area: 323802 },
  { iso3: "NPL", name: "Nepal", nameFr: "Népal", lat: 28, lng: 84, borders: ["CHN","IND"], region: "Asia", landlocked: true, area: 147181 },
  { iso3: "NRU", name: "Nauru", nameFr: "Nauru", lat: -0.53, lng: 166.92, borders: [], region: "Oceania", landlocked: false, area: 21 },
  { iso3: "NZL", name: "New Zealand", nameFr: "Nouvelle-Zélande", lat: -41, lng: 174, borders: [], region: "Oceania", landlocked: false, area: 270467 },
  { iso3: "OMN", name: "Oman", nameFr: "Oman", lat: 21, lng: 57, borders: ["SAU","ARE","YEM"], region: "Asia", landlocked: false, area: 309500 },
  { iso3: "PAK", name: "Pakistan", nameFr: "Pakistan", lat: 30, lng: 70, borders: ["AFG","CHN","IND","IRN"], region: "Asia", landlocked: false, area: 881912 },
  { iso3: "PAN", name: "Panama", nameFr: "Panama", lat: 9, lng: -80, borders: ["COL","CRI"], region: "Americas", landlocked: false, area: 75417 },
  { iso3: "PCN", name: "Pitcairn Islands", nameFr: "Îles Pitcairn", lat: -25.07, lng: -130.1, borders: [], region: "Oceania", landlocked: false, area: 47 },
  { iso3: "PER", name: "Peru", nameFr: "Pérou", lat: -10, lng: -76, borders: ["BOL","BRA","CHL","COL","ECU"], region: "Americas", landlocked: false, area: 1285216 },
  { iso3: "PHL", name: "Philippines", nameFr: "Philippines", lat: 13, lng: 122, borders: [], region: "Asia", landlocked: false, area: 342353 },
  { iso3: "PLW", name: "Palau", nameFr: "Palaos (Palau)", lat: 7.5, lng: 134.5, borders: [], region: "Oceania", landlocked: false, area: 459 },
  { iso3: "PNG", name: "Papua New Guinea", nameFr: "Papouasie-Nouvelle-Guinée", lat: -6, lng: 147, borders: ["IDN"], region: "Oceania", landlocked: false, area: 462840 },
  { iso3: "POL", name: "Poland", nameFr: "Pologne", lat: 52, lng: 20, borders: ["BLR","CZE","DEU","LTU","RUS","SVK","UKR"], region: "Europe", landlocked: false, area: 312679 },
  { iso3: "PRI", name: "Puerto Rico", nameFr: "Porto Rico", lat: 18.25, lng: -66.5, borders: [], region: "Americas", landlocked: false, area: 8870 },
  { iso3: "PRK", name: "North Korea", nameFr: "Corée du Nord", lat: 40, lng: 127, borders: ["CHN","KOR","RUS"], region: "Asia", landlocked: false, area: 120538 },
  { iso3: "PRT", name: "Portugal", nameFr: "Portugal", lat: 39.5, lng: -8, borders: ["ESP"], region: "Europe", landlocked: false, area: 92090 },
  { iso3: "PRY", name: "Paraguay", nameFr: "Paraguay", lat: -23, lng: -58, borders: ["ARG","BOL","BRA"], region: "Americas", landlocked: true, area: 406752 },
  { iso3: "PSE", name: "Palestine", nameFr: "Palestine", lat: 31.9, lng: 35.2, borders: ["ISR","EGY","JOR"], region: "Asia", landlocked: false, area: 6220 },
  { iso3: "PYF", name: "French Polynesia", nameFr: "Polynésie française", lat: -15, lng: -140, borders: [], region: "Oceania", landlocked: false, area: 4167 },
  { iso3: "QAT", name: "Qatar", nameFr: "Qatar", lat: 25.5, lng: 51.25, borders: ["SAU"], region: "Asia", landlocked: false, area: 11586 },
  { iso3: "REU", name: "Réunion", nameFr: "Réunion", lat: -21.15, lng: 55.5, borders: [], region: "Africa", landlocked: false, area: 2511 },
  { iso3: "ROU", name: "Romania", nameFr: "Roumanie", lat: 46, lng: 25, borders: ["BGR","HUN","MDA","SRB","UKR"], region: "Europe", landlocked: false, area: 238391 },
  { iso3: "RUS", name: "Russia", nameFr: "Russie", lat: 60, lng: 100, borders: ["AZE","BLR","CHN","EST","FIN","GEO","KAZ","PRK","LVA","LTU","MNG","NOR","POL","UKR"], region: "Europe", landlocked: false, area: 17098242 },
  { iso3: "RWA", name: "Rwanda", nameFr: "Rwanda", lat: -2, lng: 30, borders: ["BDI","COD","TZA","UGA"], region: "Africa", landlocked: true, area: 26338 },
  { iso3: "SAU", name: "Saudi Arabia", nameFr: "Arabie Saoudite", lat: 25, lng: 45, borders: ["IRQ","JOR","KWT","OMN","QAT","ARE","YEM"], region: "Asia", landlocked: false, area: 2149690 },
  { iso3: "SDN", name: "Sudan", nameFr: "Soudan", lat: 15, lng: 30, borders: ["CAF","TCD","EGY","ERI","ETH","LBY","SSD"], region: "Africa", landlocked: false, area: 1886068 },
  { iso3: "SEN", name: "Senegal", nameFr: "Sénégal", lat: 14, lng: -14, borders: ["GMB","GIN","GNB","MLI","MRT"], region: "Africa", landlocked: false, area: 196722 },
  { iso3: "SGP", name: "Singapore", nameFr: "Singapour", lat: 1.37, lng: 103.8, borders: [], region: "Asia", landlocked: false, area: 710 },
  { iso3: "SGS", name: "South Georgia", nameFr: "Géorgie du Sud-et-les Îles Sandwich du Sud", lat: -54.5, lng: -37, borders: [], region: "Antarctic", landlocked: false, area: 3903 },
  { iso3: "SHN", name: "Saint Helena, Ascension and Tristan da Cunha", nameFr: "Sainte-Hélène, Ascension et Tristan da Cunha", lat: -15.95, lng: -5.72, borders: [], region: "Africa", landlocked: false, area: 394 },
  { iso3: "SJM", name: "Svalbard and Jan Mayen", nameFr: "Svalbard et Jan Mayen", lat: 78, lng: 20, borders: [], region: "Europe", landlocked: false, area: -1 },
  { iso3: "SLB", name: "Solomon Islands", nameFr: "Îles Salomon", lat: -8, lng: 159, borders: [], region: "Oceania", landlocked: false, area: 28896 },
  { iso3: "SLE", name: "Sierra Leone", nameFr: "Sierra Leone", lat: 8.5, lng: -11.5, borders: ["GIN","LBR"], region: "Africa", landlocked: false, area: 71740 },
  { iso3: "SLV", name: "El Salvador", nameFr: "Salvador", lat: 13.83, lng: -88.92, borders: ["GTM","HND"], region: "Americas", landlocked: false, area: 21041 },
  { iso3: "SMR", name: "San Marino", nameFr: "Saint-Marin", lat: 43.77, lng: 12.42, borders: ["ITA"], region: "Europe", landlocked: true, area: 61 },
  { iso3: "SOM", name: "Somalia", nameFr: "Somalie", lat: 10, lng: 49, borders: ["DJI","ETH","KEN"], region: "Africa", landlocked: false, area: 637657 },
  { iso3: "SPM", name: "Saint Pierre and Miquelon", nameFr: "Saint-Pierre-et-Miquelon", lat: 46.83, lng: -56.33, borders: [], region: "Americas", landlocked: false, area: 242 },
  { iso3: "SRB", name: "Serbia", nameFr: "Serbie", lat: 44, lng: 21, borders: ["BIH","BGR","HRV","HUN","UNK","MKD","MNE","ROU"], region: "Europe", landlocked: true, area: 88361 },
  { iso3: "SSD", name: "South Sudan", nameFr: "Soudan du Sud", lat: 7, lng: 30, borders: ["CAF","COD","ETH","KEN","SDN","UGA"], region: "Africa", landlocked: true, area: 619745 },
  { iso3: "STP", name: "São Tomé and Príncipe", nameFr: "São Tomé et Príncipe", lat: 1, lng: 7, borders: [], region: "Africa", landlocked: false, area: 964 },
  { iso3: "SUR", name: "Suriname", nameFr: "Surinam", lat: 4, lng: -56, borders: ["BRA","GUF","GUY"], region: "Americas", landlocked: false, area: 163820 },
  { iso3: "SVK", name: "Slovakia", nameFr: "Slovaquie", lat: 48.67, lng: 19.5, borders: ["AUT","CZE","HUN","POL","UKR"], region: "Europe", landlocked: true, area: 49037 },
  { iso3: "SVN", name: "Slovenia", nameFr: "Slovénie", lat: 46.12, lng: 14.82, borders: ["AUT","HRV","ITA","HUN"], region: "Europe", landlocked: false, area: 20273 },
  { iso3: "SWE", name: "Sweden", nameFr: "Suède", lat: 62, lng: 15, borders: ["FIN","NOR"], region: "Europe", landlocked: false, area: 450295 },
  { iso3: "SWZ", name: "Eswatini", nameFr: "Eswatini", lat: -26.5, lng: 31.5, borders: ["MOZ","ZAF"], region: "Africa", landlocked: true, area: 17364 },
  { iso3: "SXM", name: "Sint Maarten", nameFr: "Saint-Martin", lat: 18.03, lng: -63.05, borders: ["MAF"], region: "Americas", landlocked: false, area: 34 },
  { iso3: "SYC", name: "Seychelles", nameFr: "Seychelles", lat: -4.58, lng: 55.67, borders: [], region: "Africa", landlocked: false, area: 452 },
  { iso3: "SYR", name: "Syria", nameFr: "Syrie", lat: 35, lng: 38, borders: ["IRQ","ISR","JOR","LBN","TUR"], region: "Asia", landlocked: false, area: 185180 },
  { iso3: "TCA", name: "Turks and Caicos Islands", nameFr: "Îles Turques-et-Caïques", lat: 21.75, lng: -71.58, borders: [], region: "Americas", landlocked: false, area: 948 },
  { iso3: "TCD", name: "Chad", nameFr: "Tchad", lat: 15, lng: 19, borders: ["CMR","CAF","LBY","NER","NGA","SDN"], region: "Africa", landlocked: true, area: 1284000 },
  { iso3: "TGO", name: "Togo", nameFr: "Togo", lat: 8, lng: 1.17, borders: ["BEN","BFA","GHA"], region: "Africa", landlocked: false, area: 56785 },
  { iso3: "THA", name: "Thailand", nameFr: "Thaïlande", lat: 15, lng: 100, borders: ["MMR","KHM","LAO","MYS"], region: "Asia", landlocked: false, area: 513120 },
  { iso3: "TJK", name: "Tajikistan", nameFr: "Tadjikistan", lat: 39, lng: 71, borders: ["AFG","CHN","KGZ","UZB"], region: "Asia", landlocked: true, area: 143100 },
  { iso3: "TKL", name: "Tokelau", nameFr: "Tokelau", lat: -9, lng: -172, borders: [], region: "Oceania", landlocked: false, area: 12 },
  { iso3: "TKM", name: "Turkmenistan", nameFr: "Turkménistan", lat: 40, lng: 60, borders: ["AFG","IRN","KAZ","UZB"], region: "Asia", landlocked: true, area: 488100 },
  { iso3: "TLS", name: "Timor-Leste", nameFr: "Timor oriental", lat: -8.83, lng: 125.92, borders: ["IDN"], region: "Asia", landlocked: false, area: 14874 },
  { iso3: "TON", name: "Tonga", nameFr: "Tonga", lat: -20, lng: -175, borders: [], region: "Oceania", landlocked: false, area: 747 },
  { iso3: "TTO", name: "Trinidad and Tobago", nameFr: "Trinité-et-Tobago", lat: 11, lng: -61, borders: [], region: "Americas", landlocked: false, area: 5130 },
  { iso3: "TUN", name: "Tunisia", nameFr: "Tunisie", lat: 34, lng: 9, borders: ["DZA","LBY"], region: "Africa", landlocked: false, area: 163610 },
  { iso3: "TUR", name: "Türkiye", nameFr: "Turquie", lat: 39, lng: 35, borders: ["ARM","AZE","BGR","GEO","GRC","IRN","IRQ","SYR"], region: "Asia", landlocked: false, area: 783562 },
  { iso3: "TUV", name: "Tuvalu", nameFr: "Tuvalu", lat: -8, lng: 178, borders: [], region: "Oceania", landlocked: false, area: 26 },
  { iso3: "TWN", name: "Taiwan", nameFr: "Taïwan", lat: 23.5, lng: 121, borders: [], region: "Asia", landlocked: false, area: 36193 },
  { iso3: "TZA", name: "Tanzania", nameFr: "Tanzanie", lat: -6, lng: 35, borders: ["BDI","COD","KEN","MWI","MOZ","RWA","UGA","ZMB"], region: "Africa", landlocked: false, area: 945087 },
  { iso3: "UGA", name: "Uganda", nameFr: "Ouganda", lat: 1, lng: 32, borders: ["COD","KEN","RWA","SSD","TZA"], region: "Africa", landlocked: true, area: 241550 },
  { iso3: "UKR", name: "Ukraine", nameFr: "Ukraine", lat: 49, lng: 32, borders: ["BLR","HUN","MDA","POL","ROU","RUS","SVK"], region: "Europe", landlocked: false, area: 603500 },
  { iso3: "UMI", name: "United States Minor Outlying Islands", nameFr: "Îles mineures éloignées des États-Unis", lat: 19.3, lng: 166.63, borders: [], region: "Americas", landlocked: false, area: 34 },
  { iso3: "UNK", name: "Kosovo", nameFr: "Kosovo", lat: 42.67, lng: 21.17, borders: ["ALB","MKD","MNE","SRB"], region: "Europe", landlocked: true, area: 10908 },
  { iso3: "URY", name: "Uruguay", nameFr: "Uruguay", lat: -33, lng: -56, borders: ["ARG","BRA"], region: "Americas", landlocked: false, area: 181034 },
  { iso3: "USA", name: "United States", nameFr: "États-Unis", lat: 38, lng: -97, borders: ["CAN","MEX"], region: "Americas", landlocked: false, area: 9372610 },
  { iso3: "UZB", name: "Uzbekistan", nameFr: "Ouzbékistan", lat: 41, lng: 64, borders: ["AFG","KAZ","KGZ","TJK","TKM"], region: "Asia", landlocked: true, area: 447400 },
  { iso3: "VAT", name: "Vatican City", nameFr: "Cité du Vatican", lat: 41.9, lng: 12.45, borders: ["ITA"], region: "Europe", landlocked: true, area: 0 },
  { iso3: "VCT", name: "Saint Vincent and the Grenadines", nameFr: "Saint-Vincent-et-les-Grenadines", lat: 13.25, lng: -61.2, borders: [], region: "Americas", landlocked: false, area: 389 },
  { iso3: "VEN", name: "Venezuela", nameFr: "Venezuela", lat: 8, lng: -66, borders: ["BRA","COL","GUY"], region: "Americas", landlocked: false, area: 916445 },
  { iso3: "VGB", name: "British Virgin Islands", nameFr: "Îles Vierges britanniques", lat: 18.43, lng: -64.62, borders: [], region: "Americas", landlocked: false, area: 151 },
  { iso3: "VIR", name: "United States Virgin Islands", nameFr: "Îles Vierges des États-Unis", lat: 18.35, lng: -64.93, borders: [], region: "Americas", landlocked: false, area: 347 },
  { iso3: "VNM", name: "Vietnam", nameFr: "Viêt Nam", lat: 16.17, lng: 107.83, borders: ["KHM","CHN","LAO"], region: "Asia", landlocked: false, area: 331212 },
  { iso3: "VUT", name: "Vanuatu", nameFr: "Vanuatu", lat: -16, lng: 167, borders: [], region: "Oceania", landlocked: false, area: 12189 },
  { iso3: "WLF", name: "Wallis and Futuna", nameFr: "Wallis-et-Futuna", lat: -13.3, lng: -176.2, borders: [], region: "Oceania", landlocked: false, area: 142 },
  { iso3: "WSM", name: "Samoa", nameFr: "Samoa", lat: -13.58, lng: -172.33, borders: [], region: "Oceania", landlocked: false, area: 2842 },
  { iso3: "YEM", name: "Yemen", nameFr: "Yémen", lat: 15, lng: 48, borders: ["OMN","SAU"], region: "Asia", landlocked: false, area: 527968 },
  { iso3: "ZAF", name: "South Africa", nameFr: "Afrique du Sud", lat: -29, lng: 24, borders: ["BWA","LSO","MOZ","NAM","SWZ","ZWE"], region: "Africa", landlocked: false, area: 1221037 },
  { iso3: "ZMB", name: "Zambia", nameFr: "Zambie", lat: -15, lng: 30, borders: ["AGO","BWA","COD","MWI","MOZ","NAM","TZA","ZWE"], region: "Africa", landlocked: true, area: 752612 },
  { iso3: "ZWE", name: "Zimbabwe", nameFr: "Zimbabwe", lat: -20, lng: 30, borders: ["BWA","MOZ","ZAF","ZMB"], region: "Africa", landlocked: true, area: 390757 },
];

export const COUNTRY_BY_ISO: Record<string, Country> = Object.fromEntries(
  COUNTRIES.map((c) => [c.iso3, c]),
);
